server:
  port: 8081
logging:
  level:
    org:
      springframework:
        security: DEBUG

keycloak:
  base-url: ${KEYCLOAK_BASE_URL}
  client-realm: ${KEYCLOAK_REALM_NAME}
  client-id: ${KEYCLOAK_CLIENT_ID}
  jwt-url: ${keycloak.base-url}/realms/${keycloak.client-realm}/protocol/openid-connect/token
  logout-url: ${keycloak.base-url}/realms/${keycloak.client-realm}/protocol/openid-connect/logout
  client-secret: ${KEYCLOAK_CLIENT_SECRET}
spring:
  application:
    name: service
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: ${keycloak.client-id}
            authorizationGrantType: authorization_code
            clientSecret: ${keycloak.client-secret}
            scope: openid
        provider:
          keycloak:
            issuerUri: ${keycloak.base-url}/realms/${keycloak.client-realm}
      resourceserver:
        jwt:
          issuer-uri: ${keycloak.base-url}/realms/${keycloak.client-realm}
          jwk-set-uri: ${keycloak.base-url}/realms/${keycloak.client-realm}/protocol/openid-connect/certs